[tool.poetry]
name = "bids-ngff-tools"
version = "0.1.0"
description = ""
authors = ["Ali Khan <alik@robarts.ca>"]
license = "MIT"
readme = "README.md"
packages = [{include = "bids_ngff_tools"}]


[tool.poetry.scripts]
bids-ngff-tools = "bids_ngff_tools.main:app"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
typer = {extras = ["all"], version = "^0.9.0"}
zarr = "^2.17.0"
nibabel = "^5.2.0"
dask = "^2024.2.0"
numpy = "^1.26.4"
scipy = "^1.12.0"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

